### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [tago-io/tago-sdk-python#18]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 3.0.8. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary tago -w /tmp/ext tago==3.0.8
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting tago==3.0.8
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/88b/83c3433f626ee/tago-3.0.8.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-hiy_haiw/tago/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-hiy_haiw/tago/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-hiy_haiw/tago/pip-egg-info
         cwd: /tmp/pip-wheel-hiy_haiw/tago/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-hiy_haiw/tago/setup.py", line 8, in <module>
        with open('requirements.txt', 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by felipefdl** [comment]
@thatch I'm not sure what you doing. But I just fire up a docker on using python3.7, the install was completely with success.

Also, the requirements.txt is not on package because it's load up on pip package build. You can see it, just download the package, unpack it, and go to ./tago.egg-info/requires.txt

If you need make a strange installation of that package, feel free to open a PR with your changes, if it make senses I can merge it without problems.

Thank you

![image](https://user-images.githubusercontent.com/3098271/82521429-10f33880-9afd-11ea-829b-dbcdfd4a8312.png)

**Comment by thatch** [comment]
Just created #19
